name: main
on: [push]

jobs:
  build:
    name: build
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: dep
        run: python -m pip install conan

      - name: gen
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build --config Debug --parallel
      
      - name: test
        run: cd build/test && ctest -V
